;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	indent-rigidly-right-to-tab-stop
	kill-region
	markdown-outdent-or-delete
	py-indent-or-complete
	))

(setq mc/cmds-to-run-once
      '(
	indent-rigidly
	mouse-set-region
	py-electric-delete
	suspend-frame
	))
