---
- name: Install brave - Download .deb package
  get_url:
    url="https://github.com/brave/brave-browser/releases/download/v1.44.43/brave-browser-nightly_1.44.43_amd64.deb"
    dest="/home/{{ username }}/Downloads/brave.deb"

- name: Install brave - Installing .deb package
  apt: deb="/home/{{ username }}/Downloads/brave.deb"
# Not working
# - name: Install brave
#   become: true
#   apt_key:
#     url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
#     state: present

# - name: Install brave - adding repository
#   become: true
#   apt_repository:
#     repo: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
#     state: present
#     filename: brave-browser-release.list
#     update_cache: yes

# - name: Install brave - installing with apt
#   become: true
#   apt:
#     name: brave-browser
#     state: present
#     update_cache: true