---
- name: Install Flatpak
  become: true
  apt:
    name: flatpak
    state: present

- name: Install Flatpak - flathub flatpak repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system