---
- name: Install obsidian - Download .deb package
  get_url:
    url="https://github.com/obsidianmd/obsidian-releases/releases/download/v0.15.9/obsidian_0.15.9_amd64.deb"
    dest="/home/{{ username }}/Downloads/obsidian.deb"

- name: Install obsidian - Installing .deb package
  apt: deb="/home/{{ username }}/Downloads/obsidian.deb"
  sudo: true
