---
- name: Installing sublime-text
  become: true
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: latest

- name: Something
  become: true
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: latest
    filename: sublime-text.list
    update_cache: yes

- name: Another someting
  become: true
  apt:
    name: sublime-text
    state: latest
    update_cache: true

- name: Install sublimetext - copy configs
  copy:
    src: "/dotfiles/utils/Sublime/User"
    dest: "/home/{{ username }}/sublime-text/Packages"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700