---
- name: Install sublime-text
  become: true
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Install sublime-text - adding repository
  become: true
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: present
    filename: sublime-text.list
    update_cache: yes

- name: Install sublime-text - installing with apt
  become: true
  apt:
    name: sublime-text
    state: present
    update_cache: true

- name: Install sublimetext - copy configs
  copy:
    src: "/home/{{ username }}/Desktop/dotfiles/utils/Sublime/User/"
    dest: "/home/{{ username }}/.config/sublime-text/Packages/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700