---
- name: Install terminator
  become: true
  apt:
    name: terminator
    state: latest
    update_cache: yes

- name: Install terminator - copy terminator config
  copy:
    src: "../files/config"
    dest: "/home/{{ username }}/.config/terminator"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644